module.exports = {
    terms: [
        "5 Ojos",
        "5 eyes",
        "Actividades de espionaje",
        "Acuerdo Comercial UE-Mercosur",
        "Acuerdo Económico y Comercial Global",
        "Acuerdo Integral y Progresista de Asociación Transpacífica",
        "Acuerdo de defensa mutua",
        "Acuerdos de ayuda mutua",
        "Acuerdos de control de armamentos",
        "Acuerdos de libre comercio",
        "Acuerdo de libre comercio",
        "Acuerdos de paz",
        "Acuerdo de paz",
        "Aeropuerto militar",
        "Afganistán",
        "Agua potable",
        "Aguas internacionales",
        "Al-Qaeda",
        "Alianza militar",
        "Alto Mando",
        "Amenaza persistente avanzada (APT)",
        "Análisis de inteligencia",
        "Análisis geoespacial",
        "Aplicación de aduanas",
        "Aprendizaje automático en seguridad",
        "Arabia Saudita",
        "Archipiélago de Chagos",
        "Armas de destrucción masiva",
        "Armas de guerra",
        "Armas químicas",
        "Armas radiológicas",
        "Artillería",
        "Artillería de campaña",
        "Asimetría militar",
        "Asociación Europea de Libre Comercio",
        "Asociación Transpacífica",
        "Ataque terrorista",
        "Autopistas cortadas",
        "Aviación",
        "Azerbaiyán",
        "Balcanización",
        "Base Logística",
        "Base Militar",
        "Biometría",
        "Bioterrorismo",
        "Búnkeres",
        "Búsqueda y rescate",
        "CIA",
        "CNI",
        "Cable submarino",
        "Cables submarinos",
        "Cachemira",
        "Canal de Panamá",
        "Canal de Suez",
        "Capacidad de disuasión",
        "Centro Nacional de Criptología",
        "Centro Nacional de Inteligencia",
        "Centro de datos",
        "Centros de datos",
        "Centros de fusión",
        "China",
        "Ciberdefensa",
        "Ciberdesinformación",
        "Ciberpropaganda",
        "Ciberseguridad",
        "Ciberterrorismo",
        "Cinco Ojos",
        "Colaboración internacional",
        "Comando conjunto",
        "Combate mecanizado",
        "Combatientes extranjeros",
        "Computación en la nube",
        "Comunicaciones de emergencia",
        "Conciencia del dominio marítimo",
        "Conflicto armado",
        "Conflicto bélico",
        "Conflicto de baja intensidad",
        "Conflicto híbrido",
        "Conflicto territorial",
        "Conflicto étnico",
        "Consejo de Seguridad de la ONU",
        "Contrainsurgencia",
        "Contrainteligencia",
        "Contraterrorismo",
        "Control de armas",
        "Cooperación internacional en defensa",
        "Corea del Norte",
        "Corea del Sur",
        "Corredores de transporte",
        "Cuenca del Amazonas",
        "Cuenca del Congo",
        "Cuerno de África",
        "Cumbre de Paz",
        "Cáucaso",
        "DARPA",
        "Defensa antimisiles",
        "Defensa aérea",
        "Defensa colectiva",
        "Defensa en profundidad",
        "Defensa territorial",
        "Desinformación",
        "Desinformación y propaganda",
        "Desradicalización",
        "Diplomacia militar",
        "Dispositivo de reconocimiento",
        "Dispositivo de vigilancia",
        "Disputa fronteriza",
        "Disuasión estratégica",
        "Disuasión nuclear",
        "Doctrina de seguridad nacional",
        "Doctrina militar",
        "Drones de combate",
        "Echelon",
        "Egipto",
        "Ejército del Aire",
        "Eliminación de artefactos explosivos",
        "Emiratos Árabes Unidos",
        "Encriptación de datos",
        "Energía renovable",
        "Entrenamiento antiterrorista",
        "Entrenamiento militar",
        "Equilibrio de poder",
        "Equipamiento militar",
        "Equipo de respuesta especial",
        "Escalada del conflicto",
        "Escudo antimisiles",
        "Esferas de influencia",
        "Espionaje",
        "Estado Islámico",
        "Estrategia de seguridad nacional",
        "Estrategia militar",
        "Estrecho de Malaca",
        "Estrecho de Ormuz",
        "Estrecho de Taiwán",
        "Evaluación de amenazas",
        "Evaluación de riesgos",
        "Exploit de día cero",
        "Explotación de día cero",
        "Extremismo violento",
        "F-16",
        "Financiación del terrorismo",
        "Five eyes",
        "Frenchelon",
        "Frontera entre China y Nepal",
        "Frontera entre Corea del Norte y Corea del Sur",
        "Frontera entre India y China",
        "Frontera entre India y Pakistán",
        "Frontera entre Israel y Palestina",
        "Frontera entre Turquía y Siria",
        "Frontera entre Ucrania y Rusia",
        "Fuerza aérea",
        "Fuerza de intervención rápida",
        "Fuerza de tarea conjunta",
        "Fuerzas irregulares",
        "Fuerzas multinacionales",
        "Galio",
        "Gas natural",
        "Gasoducto",
        "Geoestrategia",
        "Geovallas",
        "Germanio",
        "Gestión de crisis",
        "Gigavatios",
        "GW",
        "Golfo Pérsico",
        "Golfo de Adén",
        "Grupos insurgentes",
        "Guerra asimétrica",
        "Guerra cibernética",
        "Guerra de desgaste",
        "Guerra de información",
        "Guerra de maniobras",
        "Guerra de tercera generación",
        "Guerra de trincheras",
        "Guerra económica",
        "Guerra electrónica",
        "Guerra híbrida",
        "Guerra móvil",
        "Guerra psicológica",
        "Guerras proxy",
        "HIMARS",
        "ISIS",
        "Incidente de víctimas en masa",
        "India",
        "Infantería",
        "Infraestructura crítica",
        "Infraestructuras críticas",
        "Ingeniería social",
        "Instituto Nacional de Ciberseguridad",
        "Inteligencia artificial en defensa",
        "Inteligencia de amenazas",
        "Inteligencia de comunicaciones",
        "Inteligencia de fuentes abiertas",
        "Inteligencia de señales (SIGINT)",
        "Inteligencia militar",
        "Inteligencia técnica",
        "Interferencia extranjera",
        "Internet de banda ancha",
        "Intervenciones telefónicas",
        "Intervención militar",
        "Investigación antiterrorista",
        "Irak",
        "Irán",
        "Islas Diaoyu",
        "Islas Kuriles",
        "Islas Senkaku",
        "Japón",
        "Kazajistán",
        "Labores de reconocimiento",
        "Labores de vigilancia",
        "Legislación antiterrorista",
        "Lethal autonomous weapons",
        "Litio",
        "Logística avanzada",
        "Long-range air defense",
        "Maniobras militares",
        "Manipulación de medios",
        "Mar Mediterráneo Oriental",
        "Mar Negro",
        "Mar de China Meridional",
        "Mercosur",
        "Ministerio de Defensa",
        "Misil",
        "Misiles",
        "Misión de entrenamiento",
        "Modernización militar",
        "Monitoreo de comunicaciones",
        "Movilidad táctica",
        "Multilateralismo",
        "Multipolaridad",
        "Negociación de rehenes",
        "Nigeria",
        "Nivel de amenaza terrorista",
        "OSINT",
        "OTAN",
        "Oleoducto",
        "Open Source Intelligence",
        "Operaciones combinadas",
        "Operaciones de flanqueo",
        "Operaciones de influencia",
        "Operaciones de mantenimiento de la paz",
        "Operaciones de paz",
        "Operaciones encubiertas",
        "Operaciones especiales",
        "Operaciones mecanizadas",
        "Operaciones psicológicas",
        "Organización Mundial del Comercio",
        "Organización para la Seguridad y la Cooperación en Europa (OSCE)",
        "Pandemia mundial",
        "Pakistán",
        "Patrulla fronteriza",
        "Península Arábiga",
        "Península de Crimea",
        "Petrodólar",
        "Petróleo",
        "Piratería marítima",
        "Planificación estratégica",
        "Poder blando",
        "Poder duro",
        "Poder naval",
        "Policía militar",
        "Policía secreta",
        "Política de defensa",
        "Política exterior",
        "Portaaviones",
        "Preparación en salud pública",
        "Presupuesto de defensa",
        "Prevención del terrorismo",
        "Proliferación nuclear",
        "Propaganda desinformación",
        "Propaganda y desinformación",
        "Protección de infraestructura crítica",
        "Protección de infraestructuras",
        "Proveedores de servicios de Internet",
        "Puertos marítimos",
        "Putin",
        "Qatar",
        "Radicalización",
        "Realidad virtual en entrenamiento",
        "Recuperación de activos",
        "Recursos minerales",
        "Red ferroviaria",
        "Redes de telecomunicaciones",
        "Redes de vigilancia",
        "Redes inalámbricas",
        "Redes móviles",
        "Redes privadas virtuales (VPNs)",
        "Redes terroristas",
        "Refugio antinuclear",
        "Refugio nuclear",
        "Refugios antinucleares",
        "Refugios nucleares",
        "Región de los Balcanes",
        "Región del Magreb",
        "Región del Ártico",
        "Relaciones diplomáticas",
        "Relaciones geopolíticas",
        "Respuesta a incidentes",
        "Respuesta de emergencia",
        "Respuestas a ataques terroristas",
        "Robótica en defensa",
        "Robótica militar",
        "Rusia",
        "Ruta de la Seda",
        "SITEL",
        "STONEGHOST",
        "Sabotaje",
        "Sahel",
        "Satélite",
        "Satélites de comunicación",
        "Seguridad aeroportuaria",
        "Seguridad alimentaria",
        "Seguridad aérea",
        "Seguridad blockchain",
        "Seguridad corporativa",
        "Seguridad de la cadena de suministro",
        "Seguridad de la información",
        "Seguridad en eventos masivos",
        "Seguridad energética",
        "Seguridad internacional",
        "Seguridad fronteriza",
        "Seguridad física",
        "Seguridad marítima",
        "Seguridad nacional",
        "Seguridad penitenciaria",
        "Seguridad portuaria",
        "Seguridad pública",
        "Servicio secreto",
        "Siria",
        "Sistemas de armamento avanzado",
        "Soberanía nacional",
        "Submarino nuclear",
        "Subversión",
        "Sudáfrica",
        "Superioridad aérea",
        "Supresión de incendios forestales",
        "TLCAN",
        "Taiwán",
        "Talibán",
        "Tántalo",
        "Tareas de reconocimiento",
        "Tareas de vigilancia",
        "Teravatios",
        "Tecnología militar",
        "Terminales de carga",
        "Terrorismo de extrema derecha",
        "Terrorismo doméstico",
        "Terrorismo internacional",
        "Terrorismo yihadista",
        "Think tank",
        "Tierra fértil",
        "Transporte aéreo",
        "Tratado de defensa mutua",
        "Transporte intermodal",
        "Transporte ferroviario",
        "Tratado de Libre Comercio",
        "Transporte marítimo",
        "Transporte terrestre",
        "Tratado de No Proliferación Nuclear",
        "Tráfico de armas",
        "Tráfico de drogas",
        "Tratado de Paz",
        "Tráfico de personas",
        "Tungsteno",
        "Turquía",
        "Tácticas militares",
        "UME",
        "Ucrania",
        "Unidad Militar de Emergencias",
        "Unidades de élite contra el terrorismo",
        "Unilateralismo",
        "Unión Europea",
        "Vehículos aéreos no tripulados (UAVs)",
        "Vigilancia aérea",
        "Vigilancia con drones",
        "XKeyscore",
        "Yuan",
        "Yuanes",
        "Zero day exploit",
        "Zona de exclusión aérea",
        "Zona del Saara Occidental",
        "activo de reserva",
        "arma autónoma letal",
        "armada",
        "armada estadounidense",
        "armas autónomas letales",
        "carrera armamentista",
        "carrera armamentística",
        "cazabombardero",
        "ciberataque",
        "Cobalto",
        "corredor humanitario",
        "crisis diplomática",
        "depósito de cobre",
        "depósito de fosfato",
        "depósito de fósforo",
        "depósito de hierro",
        "depósito de oro",
        "depósito de petróleo",
        "depósito de plata",
        "depósito de platino",
        "depósito de silicio",
        "depósito de uranio",
        "disturbios generalizados",
        "dron de reconocimiento",
        "dron militar",
        "ejército de tierra",
        "el Pentágono",
        "energía nuclear",
        "enriquecimiento de uranio",
        "escalada bélica",
        "estado fallido",
        "fosfatos",
        "fundación ESYS",
        "Grafito",
        "mina de carbón",
        "mina de cobre",
        "mina de fosfato",
        "mina de fósforo",
        "mina de hierro",
        "mina de oro",
        "mina de plata",
        "mina de platino",
        "mina de silicio",
        "mina de uranio",
        "mineral estratégico",
        "minerales estratégicos",
        "mocromafia",
        "Níquel",
        "narcotráfico internacional",
        "peak oil",
        "pico del petróleo",
        "pico petrolero",
        "presas hidroeléctricas",
        "programa Bullrun",
        "programa DISHFIRE",
        "programa Pegasus",
        "reactor de fisión",
        "reservas de cobre",
        "reservas de fosfato",
        "reservas de fósforo",
        "reservas de hierro",
        "reservas de oro",
        "reservas de petróleo",
        "reservas de plata",
        "reservas de platino",
        "reservas de silicio",
        "reservas de uranio",
        "terrorismo internacional",
        "tierras raras",
        "uranio enriquecido",
        "vehículo aéreo no tripulado",
        "zona de alta conflictividad",
        "Área de Libre Comercio Continental Africana",
        "Área de Libre Comercio de las Américas"
    ],
    websites: [
        "https://20minutos.es",
        "https://abc.es",
        "https://ambito.com",
        "https://antena3.com",
        "https://bbc.com",
        "https://cincodias.com",
        "https://cinconoticias.com",
        "https://clarin.com",
        "https://cleantechnica.es",
        "https://cnet.es",
        "https://cooperativa.cl",
        "https://critica.com.pa",
        "https://defensa.gob.es",
        "https://diario16.com",
        "https://diariodecadiz.es",
        "https://diariodenavarra.es",
        "https://diariodesevilla.es",
        "https://diariodetarragona.com",
        "https://diariovasco.com",
        "https://digitaltrends.es",
        "https://ecoinventos.com",
        "https://efe.com",
        "https://el-nacional.com",
        "https://elcolombiano.com",
        "https://elcomercio.es",
        "https://elcomercio.pe",
        "https://elconfidencial.com",
        "https://elconfidencialdigital.com",
        "https://elcorreo.com",
        "https://eldiario.es",
        "https://eleconomista.es",
        "https://elespanol.com",
        "https://elespectador.com",
        "https://elheraldo.co",
        "https://elmercurio.com",
        "https://elmostrador.cl",
        "https://elmundo.es",
        "https://elnuevodia.com",
        "https://elordenmundial.com",
        "https://elpais.com",
        "https://elpais.com.uy",
        "https://elpais.cr",
        "https://elperiodico.com",
        "https://elperiodicodelaenergia.com",
        "https://eltiempo.com",
        "https://eluniversal.com.mx",
        "https://emol.com",
        "https://europapress.es",
        "https://epe.es",
        "https://excelsior.com.mx",
        "https://expansion.com",
        "https://fundacionfaes.org",
        "https://galaxiamilitar.es",
        "https://gcn.es",
        "https://guerrasposmodernas.com",
        "https://es.gizmodo.com",
        "https://govtech.es",
        "https://huffingtonpost.es",
        "https://ideal.es",
        "https://iecah.org",
        "https://ieee.es",
        "https://infobae.com",
        "https://infodefensa.com",
        "https://jornada.com.mx",
        "https://la-razon.com",
        "https://lacuarta.com",
        "https://lainformacion.com",
        "https://lanacion.com.ar",
        "https://laprensa.hn",
        "https://larazon.es",
        "https://larepublica.co",
        "https://larepublica.pe",
        "https://latercera.com",
        "https://lavanguardia.com",
        "https://lavozdegalicia.es",
        "https://lavozdigital.es",
        "https://listindiario.com",
        "https://lne.es",
        "https://lostiempos.com",
        "https://mercurio.com",
        "https://milenio.com",
        "https://mondediplo.com",
        "https://nacion.com",
        "https://noticiasdenavarra.com",
        "https://okdiario.com",
        "https://pagina12.com.ar",
        "https://paginasiete.bo",
        "https://perfil.com",
        "https://politicaexterior.com",
        "https://prensa.com",
        "https://proceso.com.mx",
        "https://publico.es",
        "https://pv-magazine.es",
        "https://realinstitutoelcano.org",
        "https://republica.com.uy",
        "https://reuters.com",
        "https://revistaejercitos.com",
        "https://rumbominero.com",
        "https://seguridadinternacional.es",
        "https://segurilatam.com",
        "https://sputniknews.lat",
        "https://teinteresa.es",
        "https://telam.com.ar",
        "https://theobjective.com",
        "https://ultimahora.com",
        "https://vanguardia.com",
        "https://vozpopuli.com"
    ]
};
