module.exports = {
    terms: [
    "Guerra híbrida",
    "activo de reserva",
    "peak oil",
    "pico petrolero",
    "pico del petróleo",
    "Ciberseguridad",
    "Inteligencia militar",
    "Contrainsurgencia",
    "Asimetría militar",
    "Disuasión nuclear",
    "Escalada del conflicto",
    "Operaciones especiales",
    "Guerra cibernética",
    "Defensa territorial",
    "Seguridad marítima",
    "Seguridad aérea",
    "Terrorismo internacional",
    "Guerras proxy",
    "Relaciones geopolíticas",
    "Diplomacia militar",
    "Cooperación internacional en defensa",
    "Sistemas de armamento avanzado",
    "Planificación estratégica",
    "Estrategia de seguridad nacional",
    "Guerra cibernética",
    "Conflicto híbrido",
    "escalada bélica",
    "disturbios generalizados",
    "Lethal autonomous weapons",
    "armas autónomas letales",
    "arma autónoma letal",
    "carrera armamentista",
    "carrera armamentística",
    "estado fallido",
    "zona de alta conflictividad",
    "Guerra asimétrica",
    "Inteligencia artificial en defensa",
    "Robótica militar",
    "Operaciones especiales",
    "Guerra psicológica",
    "Drones de combate",
    "Seguridad energética",
    "Alianza militar",
    "Defensa colectiva",
    "Capacidad de disuasión",
    "Operaciones de paz",
    "Proliferación nuclear",
    "Control de armas",
    "Zona de exclusión aérea",
    "Defensa antimisiles",
    "Escudo antimisiles",
    "Comando conjunto",
    "Fuerza de intervención rápida",
    "Fuerza aérea",
    "Defensa aérea",
    "Misión de entrenamiento",
    "Tratado de defensa mutua",
    "Acuerdo de defensa mutua",
    "Fuerzas multinacionales",
    "Alto Mando",
    "Taiwán",
    "Ucrania",
    "Putin",
    "Doctrina militar",
    "cazabombardero",
    "HIMARS",
    "F-16",
    "uranio enriquecido",
    "enriquecimiento de uranio",
    "corredor humanitario",
    "Estrategia militar",
    "Tácticas militares",
    "Operaciones especiales",
    "Equipamiento militar",
    "Maniobras militares",
    "Presupuesto de defensa",
    "Modernización militar",
    "Entrenamiento militar",
    "Ciberdefensa",
    "Guerra electrónica",
    "Artillería",
    "Infantería",
    "Aviación",
    "Al-Qaeda",
    "Estado Islámico",
    "ISIS",
    "Talibán",
    "Ataque terrorista",
    "Radicalización",
    "Financiación del terrorismo",
    "Contrainteligencia",
    "Terrorismo doméstico",
    "terrorismo internacional",
    "Terrorismo yihadista",
    "Terrorismo de extrema derecha",
    "narcotráfico internacional",
    "mocromafia",
    "Redes terroristas",
    "Combatientes extranjeros",
    "Extremismo violento",
    "Grupos insurgentes",
    "Ciberterrorismo",
    "Armas químicas",
    "Redes de telecomunicaciones",
    "Internet de banda ancha",
    "Satélites de comunicación",
    "Submarino nuclear",    
    "Cables submarinos de fibra óptica",
    "Ciberseguridad",
    "presas hidroeléctricas",
    "Infraestructura crítica",
    "Redes móviles",
    "Redes inalámbricas",
    "Proveedores de servicios de Internet",
    "Redes privadas virtuales (VPNs)",
    "Centros de datos",
    "Centro de datos",
    "Computación en la nube",
    "Puertos marítimos",
    "Red ferroviaria",
    "Autopistas cortadas",
    "Aeropuertos",
    "Logística",
    "Transporte intermodal",
    "Corredores de transporte",
    "Transporte marítimo",
    "Transporte aéreo",
    "Transporte terrestre",
    "Transporte ferroviario",
    "Terminales de carga",
    "Petróleo",
    "Petrodólar",
    "Refugio nuclear",
    "Refugio antinuclear",
    "Refugios nucleares",
    "Refugios antinucleares",
    "Búnkeres",
    "Think tank",
    "Megavatios",
    "Gigavatios",
    "Oleoducto",
    "Gasoducto",
    "Litio",
    "tierras raras",
    "Aguas internacionales",
    "Tierra fértil",
    "Gas natural",
    "Recursos minerales",
    "Energía renovable",
    "mina de carbón",
    "mina de silicio",
    "mina de fósforo",
    "mina de uranio",
    "mina de cobre",
    "mina de hierro",
    "mina de oro",
    "mina de plata",
    "mina de platino",
    "mina de carbón",
    "reservas de uranio",
    "reservas de silicio",
    "reservas de fósforo",
    "reservas de cobre",
    "reservas de hierro",
    "reservas de oro",
    "reservas de plata",
    "reservas de platino",
    "depósito de uranio",
    "depósito de silicio",
    "depósito de fósforo",
    "depósito de cobre",
    "depósito de hierro",
    "depósito de oro",
    "depósito de plata",
    "depósito de platino",
    "minerales estratégicos",
    "mineral estratégico",
    "OTAN",
    "O.T.A.N",
    "CIA",
    "el Pentágono",
    "DARPA",
    "Agua potable",
    "Política exterior",
    "Esferas de influencia",
    "Relaciones diplomáticas",
    "Conflicto territorial",
    "Poder blando",
    "Poder duro",
    "Multilateralismo",
    "Unilateralismo",
    "Intervención militar",
    "Soberanía nacional",
    "Geoestrategia",
    "Conflicto étnico",
    "Disputa fronteriza",
    "Acuerdos de libre comercio",
    "TLCAN",
    "Asociación Transpacífica",
    "Unión Europea",
    "Portaaviones",
    "Satélite",
    "Acuerdo Económico y Comercial Global",
    "Área de Libre Comercio Continental Africana",
    "Organización Mundial del Comercio",
    "Tratado de Libre Comercio de América del Norte",
    "Mercosur",
    "Asociación Europea de Libre Comercio",
    "Tratado de Libre Comercio de Centroamérica",
    "Área de Libre Comercio de las Américas",
    "Acuerdo de Libre Comercio UE-Japón",
    "Acuerdo Integral y Progresista de Asociación Transpacífica",
    "Acuerdo Comercial UE-Mercosur",
    "Guerra híbrida",
    "Operaciones psicológicas",
    "Desinformación",
    "Guerra cibernética",
    "Operaciones encubiertas",
    "Propaganda y desinformación",
    "Desinformación y propaganda",
    "Ciberpropaganda",
    "Ciberdesinformación",
    "Propaganda desinformación",
    "Conflicto de baja intensidad",
    "Fuerzas irregulares",
    "Sabotaje",
    "Interferencia extranjera",
    "Espionaje",
    "Subversión",
    "Manipulación de medios",
    "Operaciones de influencia",
    "Guerra económica",
    "Guerra de información",
    "Guerra de tercera generación",
    "Guerra de maniobras",
    "Combate mecanizado",
    "Guerra móvil",
    "Defensa en profundidad",
    "Operaciones combinadas",
    "Logística avanzada",
    "Tecnología militar",
    "Movilidad táctica",
    "Superioridad aérea",
    "Guerra de trincheras",
    "Operaciones mecanizadas",
    "Guerra de desgaste",
    "Artillería de campaña",
    "Operaciones de flanqueo",
    "Seguridad nacional",
    "Seguridad pública",
    "Seguridad fronteriza",
    "Seguridad aérea",
    "Seguridad marítima",
    "Seguridad física",
    "Ciberseguridad",
    "Protección de infraestructura crítica",
    "Seguridad corporativa",
    "Seguridad de la información",
    "Seguridad penitenciaria",
    "Contrainteligencia",
    "Vigilancia aérea",
    "Tareas de vigilancia",
    "Labores de vigilancia",
    "Dispositivo de vigilancia",
    "Tareas de reconocimiento",
    "Labores de reconocimiento",
    "Dispositivo de reconocimiento",
    "Inteligencia de fuentes abiertas",
    "Open Source Intelligence",
    "OSINT",
    "Inteligencia técnica",
    "Inteligencia de comunicaciones",
    "Evaluación de amenazas",
    "Análisis geoespacial",
    "Inteligencia militar",
    "Contraterrorismo",
    "Prevención del terrorismo",
    "Respuestas a ataques terroristas",
    "Seguridad aeroportuaria",
    "Seguridad fronteriza",
    "Desradicalización",
    "Colaboración internacional",
    "Legislación antiterrorista",
    "5 Ojos",
    "Cinco Ojos",
    "Five eyes",
    "5 eyes",
    "ciberataque",
    "Echelon",
    "programa DISHFIRE",
    "programa Bullrun",
    "programa Pegasus",
    "Frenchelon",
    "XKeyscore",
    "STONEGHOST",
    "SITEL",
    "Infraestructuras críticas",
    "Centro Nacional de Criptología",
    "Centro Nacional de Inteligencia",
    " C.N.I. ",
    " U.M.E. ",
    "Unidad Militar de Emergencias",
    "Protección de infraestructuras",
    "Investigación antiterrorista",
    "Unidades de élite contra el terrorismo",
    "Redes de vigilancia",
    "Monitoreo de comunicaciones",
    "Seguridad en eventos masivos",
    "Entrenamiento antiterrorista",
    "Amenaza persistente avanzada (APT)",
    "Recuperación de activos",
    "Patrulla fronteriza",
    "Bioterrorismo",
    "Gestión de crisis",
    "Aplicación de aduanas",
    "Política de defensa",
    "Respuesta de emergencia",
    "Actividades de espionaje",
    "Eliminación de artefactos explosivos",
    "Negociación de rehenes",
    "Respuesta a incidentes",
    "Análisis de inteligencia",
    "Fuerza de tarea conjunta",
    "Piratería marítima",
    "Incidente de víctimas en masa",
    "Acuerdos de ayuda mutua",
    "Disuasión nuclear",
    "energía nuclear",
    "reactor de fisión",
    "Seguridad portuaria",
    "Preparación en salud pública",
    "Armas radiológicas",
    "Búsqueda y rescate",
    "Equipo de respuesta especial",
    "Disuasión estratégica",
    "Nivel de amenaza terrorista",
    "Tráfico de personas",
    "Tráfico de armas",
    "Tráfico de drogas",
    "Armas de destrucción masiva",
    "Supresión de incendios forestales",
    "Intervenciones telefónicas",
    "Biometría",
    "Seguridad blockchain",
    "Encriptación de datos",
    "Vigilancia con drones",
    "Comunicaciones de emergencia",
    "Centros de fusión",
    "Geovallas",
    "Aprendizaje automático en seguridad",
    "Conciencia del dominio marítimo",
    "Evaluación de riesgos",
    "Robótica en defensa",
    "Ingeniería social",
    "Seguridad de la cadena de suministro",
    "Inteligencia de amenazas",
    "Vehículos aéreos no tripulados (UAVs)",
    "vehículo aéreo no tripulado",
    "dron de reconocimiento",
    "dron militar",
    "ejército de tierra",
    "armada estadounidense",
    "Realidad virtual en entrenamiento",
    "Explotación de día cero",
    "Exploit de día cero",
    "Zero day exploit",
    "Instituto Nacional de Ciberseguridad",
    "fundación ESYS",
    "Poder naval",
    "Multipolaridad",
    "Balcanización",
    "Tratado de No Proliferación Nuclear",
    "Consejo de Seguridad de la ONU",
    "Operaciones de mantenimiento de la paz",
    "Ruta de la Seda",
    "Organización para la Seguridad y la Cooperación en Europa (OSCE)",
    "Doctrina de seguridad nacional",
    "Acuerdos de control de armamentos",
    "Equilibrio de poder",
    "crisis diplomática",
    "Seguridad alimentaria",
    "Inteligencia de señales (SIGINT)"
],
    websites: [
    "https://seguridadinternacional.es",
    "https://revistaejercitos.com",
    "https://infodefensa.com",
    "https://politicaexterior.com",
    "https://infodefensa.com",
    "https://realinstitutoelcano.org",
    "https://fundacionfaes.org",
    "https://iecah.org",
    "https://reuters.com/",
    "https://defensa.gob.es",
    "https://elordenmundial.com",
    "https://global-strategy.org",
    "https://eleconomista.es/",
    "https://rumbominero.com/",
    "https://ieee.es",
    "https://larazon.es",
    "https://elmundo.es",
    "https://abc.es",
    "https://elpais.com",
    "https://eldiario.es",
    "https://20minutos.es",
    "https://lavanguardia.com",
    "https://elconfidencial.com",
    "https://elespanol.com",
    "https://elpais.com",
    "https://teinteresa.es",
    "https://antena3.com",
    "https://europapress.es",
    "https://efe.com",
    "https://eldiario.es",
    "https://lavozdegalicia.es",
    "https://diariodenavarra.es",
    "https://elcomercio.es",
    "https://diariodesevilla.es",
    "https://lainformacion.com",
    "https://okdiario.com",
    "https://elespanol.com",
    "https://elconfidencialdigital.com",
    "https://theobjective.com",
    "https://revistaejercitos.com",
    "https://rebelion.org",
    "https://kaosenlared.net",
    "https://globalresearch.ca",
    "https://mondediplo.com",
    "https://sputniknews.lat",
    "https://lainformacion.com",
    "https://segurilatam.com",
    "https://gcn.es",
    "https://govtech.es",
    "https://breakingenergy.es",
    "https://pv-magazine.es",
    "https://cleantechnica.es",
    "https://gizmodo.es",
    "https://cnet.es",
    "https://digitaltrends.es"
]
};
