module.exports = {
    terms: [
        '5 Ojos',
        '5 eyes',
        'Actividades de espionaje',
        'Acuerdo Comercial UE-Mercosur',
        'Acuerdo Económico y Comercial Global',
        'Acuerdo Integral y Progresista de Asociación Transpacífica',
        'Acuerdo de Libre Comercio UE-Japón',
        'Acuerdo de defensa mutua',
        'Acuerdos de ayuda mutua',
        'Acuerdos de control de armamentos',
        'Acuerdos de libre comercio',
        'Aeropuerto militar',
        'Agua potable',
        'Aguas internacionales',
        'Al-Qaeda',
        'Alianza militar',
        'Alto Mando',
        'Amenaza persistente avanzada (APT)',
        'Análisis de inteligencia',
        'Análisis geoespacial',
        'Aplicación de aduanas',
        'Aprendizaje automático en seguridad',
        'Armas de destrucción masiva',
        'Armas químicas',
        'Armas radiológicas',
        'Artillería',
        'Artillería de campaña',
        'Asimetría militar',
        'Asociación Europea de Libre Comercio',
        'Asociación Transpacífica',
        'Ataque terrorista',
        'Autopistas cortadas',
        'Aviación',
        'Balcanización',
        'Base Logística',
        'Biometría',
        'Bioterrorismo',
        'Búnkeres',
        'Búsqueda y rescate',
        'CIA',
        'CNI',
        'Cable submarino de fibra óptica',
        'Cables submarinos de fibra óptica',
        'Capacidad de disuasión',
        'Centro Nacional de Criptología',
        'Centro Nacional de Inteligencia',
        'Centro de datos',
        'Centros de datos',
        'Centros de fusión',
        'Ciberdefensa',
        'Ciberdesinformación',
        'Ciberpropaganda',
        'Ciberseguridad',
        'Ciberseguridad',
        'Ciberseguridad',
        'Ciberterrorismo',
        'Cinco Ojos',
        'Colaboración internacional',
        'Comando conjunto',
        'Combate mecanizado',
        'Combatientes extranjeros',
        'Computación en la nube',
        'Comunicaciones de emergencia',
        'Conciencia del dominio marítimo',
        'Conflicto armado',
        'Conflicto bélico',
        'Conflicto de baja intensidad',
        'Conflicto híbrido',
        'Conflicto territorial',
        'Conflicto étnico',
        'Consejo de Seguridad de la ONU',
        'Contrainsurgencia',
        'Contrainteligencia',
        'Contrainteligencia',
        'Contraterrorismo',
        'Control de armas',
        'Cooperación internacional en defensa',
        'Corredores de transporte',
        'DARPA',
        'Defensa antimisiles',
        'Defensa aérea',
        'Defensa colectiva',
        'Defensa en profundidad',
        'Defensa territorial',
        'Desinformación',
        'Desinformación y propaganda',
        'Desradicalización',
        'Diplomacia militar',
        'Dispositivo de reconocimiento',
        'Dispositivo de vigilancia',
        'Disputa fronteriza',
        'Disuasión estratégica',
        'Disuasión nuclear',
        'Disuasión nuclear',
        'Doctrina de seguridad nacional',
        'Doctrina militar',
        'Drones de combate',
        'Echelon',
        'Ejército del Aire',
        'Eliminación de artefactos explosivos',
        'Encriptación de datos',
        'Energía renovable',
        'Entrenamiento antiterrorista',
        'Entrenamiento militar',
        'Equilibrio de poder',
        'Equipamiento militar',
        'Equipo de respuesta especial',
        'Escalada del conflicto',
        'Escudo antimisiles',
        'Esferas de influencia',
        'Espionaje',
        'Estado Islámico',
        'Estrategia de seguridad nacional',
        'Estrategia militar',
        'Evaluación de amenazas',
        'Evaluación de riesgos',
        'Exploit de día cero',
        'Explotación de día cero',
        'Extremismo violento',
        'F-16',
        'Financiación del terrorismo',
        'Five eyes',
        'Frenchelon',
        'Fuerza aérea',
        'Fuerza de intervención rápida',
        'Fuerza de tarea conjunta',
        'Fuerzas irregulares',
        'Fuerzas multinacionales',
        'Gas natural',
        'Gasoducto',
        'Geoestrategia',
        'Geovallas',
        'Gestión de crisis',
        'Gigavatios',
        'Grupos insurgentes',
        'Guerra asimétrica',
        'Guerra cibernética',
        'Guerra cibernética',
        'Guerra cibernética',
        'Guerra de desgaste',
        'Guerra de información',
        'Guerra de maniobras',
        'Guerra de tercera generación',
        'Guerra de trincheras',
        'Guerra económica',
        'Guerra electrónica',
        'Guerra híbrida',
        'Guerra híbrida',
        'Guerra móvil',
        'Guerra psicológica',
        'Guerras proxy',
        'HIMARS',
        'ISIS',
        'Incidente de víctimas en masa',
        'Infantería',
        'Infraestructura crítica',
        'Infraestructuras críticas',
        'Ingeniería social',
        'Instituto Nacional de Ciberseguridad',
        'Inteligencia artificial en defensa',
        'Inteligencia de amenazas',
        'Inteligencia de comunicaciones',
        'Inteligencia de fuentes abiertas',
        'Inteligencia de señales (SIGINT)',
        'Inteligencia militar',
        'Inteligencia militar',
        'Inteligencia técnica',
        'Interferencia extranjera',
        'Internet de banda ancha',
        'Intervenciones telefónicas',
        'Intervención militar',
        'Investigación antiterrorista',
        'Labores de reconocimiento',
        'Labores de vigilancia',
        'Legislación antiterrorista',
        'Lethal autonomous weapons',
        'Litio',
        'Logística avanzada',
        'Long-range air defense',
        'Maniobras militares',
        'Manipulación de medios',
        'Mercosur',
        'Misión de entrenamiento',
        'Modernización militar',
        'Monitoreo de comunicaciones',
        'Movilidad táctica',
        'Multilateralismo',
        'Multipolaridad',
        'Negociación de rehenes',
        'Nivel de amenaza terrorista',
        'OSINT',
        'OTAN',
        'Oleoducto',
        'Open Source Intelligence',
        'Operaciones combinadas',
        'Operaciones de flanqueo',
        'Operaciones de influencia',
        'Operaciones de mantenimiento de la paz',
        'Operaciones de paz',
        'Operaciones encubiertas',
        'Operaciones especiales',
        'Operaciones especiales',
        'Operaciones especiales',
        'Operaciones mecanizadas',
        'Operaciones psicológicas',
        'Organización Mundial del Comercio',
        'Organización para la Seguridad y la Cooperación en Europa (OSCE)',
        'Patrulla fronteriza',
        'Petrodólar',
        'Petróleo',
        'Piratería marítima',
        'Planificación estratégica',
        'Poder blando',
        'Poder duro',
        'Poder naval',
        'Política de defensa',
        'Política exterior',
        'Portaaviones',
        'Preparación en salud pública',
        'Presupuesto de defensa',
        'Prevención del terrorismo',
        'Proliferación nuclear',
        'Propaganda desinformación',
        'Propaganda y desinformación',
        'Protección de infraestructura crítica',
        'Protección de infraestructuras',
        'Proveedores de servicios de Internet',
        'Puertos marítimos',
        'Putin',
        'Radicalización',
        'Realidad virtual en entrenamiento',
        'Recuperación de activos',
        'Recursos minerales',
        'Red ferroviaria',
        'Redes de telecomunicaciones',
        'Redes de vigilancia',
        'Redes inalámbricas',
        'Redes móviles',
        'Redes privadas virtuales (VPNs)',
        'Redes terroristas',
        'Refugio antinuclear',
        'Refugio nuclear',
        'Refugios antinucleares',
        'Refugios nucleares',
        'Relaciones diplomáticas',
        'Relaciones geopolíticas',
        'Respuesta a incidentes',
        'Respuesta de emergencia',
        'Respuestas a ataques terroristas',
        'Robótica en defensa',
        'Robótica militar',
        'Ruta de la Seda',
        'SITEL',
        'STONEGHOST',
        'Sabotaje',
        'Satélite',
        'Satélites de comunicación',
        'Seguridad aeroportuaria',
        'Seguridad alimentaria',
        'Seguridad aérea',
        'Seguridad aérea',
        'Seguridad blockchain',
        'Seguridad corporativa',
        'Seguridad de la cadena de suministro',
        'Seguridad de la información',
        'Seguridad en eventos masivos',
        'Seguridad energética',
        'Seguridad fronteriza',
        'Seguridad fronteriza',
        'Seguridad física',
        'Seguridad marítima',
        'Seguridad marítima',
        'Seguridad nacional',
        'Seguridad penitenciaria',
        'Seguridad portuaria',
        'Seguridad pública',
        'Sistemas de armamento avanzado',
        'Soberanía nacional',
        'Submarino nuclear',
        'Subversión',
        'Superioridad aérea',
        'Supresión de incendios forestales',
        'TLCAN',
        'Taiwán',
        'Talibán',
        'Tareas de reconocimiento',
        'Tareas de vigilancia',
        'Tecnología militar',
        'Terminales de carga',
        'Terrorismo de extrema derecha',
        'Terrorismo doméstico',
        'Terrorismo internacional',
        'Terrorismo yihadista',
        'Think tank',
        'Tierra fértil',
        'Transporte aéreo',
        'Transporte ferroviario',
        'Transporte intermodal',
        'Transporte marítimo',
        'Transporte terrestre',
        'Tratado de Libre Comercio de América del Norte',
        'Tratado de Libre Comercio de Centroamérica',
        'Tratado de No Proliferación Nuclear',
        'Tratado de defensa mutua',
        'Tráfico de armas',
        'Tráfico de drogas',
        'Tráfico de personas',
        'Tácticas militares',
        'UME',
        'Ucrania',
        'Unidad Militar de Emergencias',
        'Unidades de élite contra el terrorismo',
        'Unilateralismo',
        'Unión Europea',
        'Vehículos aéreos no tripulados (UAVs)',
        'Vigilancia aérea',
        'Vigilancia con drones',
        'XKeyscore',
        'Yuan',
        'Yuanes',
        'Zero day exploit',
        'Zona de exclusión aérea',
        'activo de reserva',
        'arma autónoma letal',
        'armada estadounidense',
        'armas autónomas letales',
        'carrera armamentista',
        'carrera armamentística',
        'cazabombardero',
        'ciberataque',
        'corredor humanitario',
        'crisis diplomática',
        'depósito de cobre',
        'depósito de fosfato',
        'depósito de fósforo',
        'depósito de hierro',
        'depósito de oro',
        'depósito de petróleo',
        'depósito de plata',
        'depósito de platino',
        'depósito de silicio',
        'depósito de uranio',
        'disturbios generalizados',
        'dron de reconocimiento',
        'dron militar',
        'ejército de tierra',
        'el Pentágono',
        'energía nuclear',
        'enriquecimiento de uranio',
        'escalada bélica',
        'estado fallido',
        'fosfatos',
        'fundación ESYS',
        'mina de carbón',
        'mina de carbón',
        'mina de cobre',
        'mina de fosfato',
        'mina de fósforo',
        'mina de hierro',
        'mina de oro',
        'mina de plata',
        'mina de platino',
        'mina de silicio',
        'mina de uranio',
        'mineral estratégico',
        'minerales estratégicos',
        'mocromafia',
        'narcotráfico internacional',
        'peak oil',
        'pico del petróleo',
        'pico petrolero',
        'presas hidroeléctricas',
        'programa Bullrun',
        'programa DISHFIRE',
        'programa Pegasus',
        'reactor de fisión',
        'reservas de cobre',
        'reservas de fosfato',
        'reservas de fósforo',
        'reservas de hierro',
        'reservas de oro',
        'reservas de petróleo',
        'reservas de plata',
        'reservas de platino',
        'reservas de silicio',
        'reservas de uranio',
        'terrorismo internacional',
        'tierras raras',
        'uranio enriquecido',
        'vehículo aéreo no tripulado',
        'zona de alta conflictividad',
        'Área de Libre Comercio Continental Africana',
        'Área de Libre Comercio de las Américas'
    ],
    websites: [
        'https://20minutos.es',
        'https://abc.es',
        'https://antena3.com',
        'https://bbc.com',
        'https://breakingenergy.es',
        'https://cleantechnica.es',
        'https://cnet.es',
        'https://defensa.gob.es',
        'https://diariodenavarra.es',
        'https://digitaltrends.es',
        'https://efe.com',
        'https://elcomercio.es',
        'https://elconfidencial.com',
        'https://elconfidencialdigital.com',
        'https://eldiario.es',
        'https://eleconomista.es',
        'https://elespanol.com',
        'https://elmundo.es',
        'https://elordenmundial.com',
        'https://elpais.com',
        'https://europapress.es',
        'https://fundacionfaes.org',
        'https://gcn.es',
        'https://gizmodo.es',
        'https://global-strategy.org',
        'https://globalresearch.ca',
        'https://govtech.es',
        'https://iecah.org',
        'https://ieee.es',
        'https://infodefensa.com',
        'https://kaosenlared.net',
        'https://lainformacion.com',
        'https://larazon.es',
        'https://lavanguardia.com',
        'https://lavozdegalicia.es',
        'https://mondediplo.com',
        'https://okdiario.com',
        'https://politicaexterior.com',
        'https://pv-magazine.es',
        'https://realinstitutoelcano.org',
        'https://rebelion.org',
        'https://reuters.com',
        'https://revistaejercitos.com',
        'https://rumbominero.com',
        'https://seguridadinternacional.es',
        'https://segurilatam.com',
        'https://sputniknews.lat',
        'https://teinteresa.es',
        'https://theobjective.com',
        'https://vozpopuli.com/'
    ]
};
